version: '3.8'

services:
  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: myecoria
      MYSQL_PASSWORD: custom_password
      MYSQL_DATABASE: custom_db
    ports:
      - "3306:3306"
    networks:
      - mysql-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-server
      MYSQL_USER: myecoria
      MYSQL_PASSWORD: custom_password
    ports:
      - "8080:80"
    depends_on:
      - mysql-server
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge